import { z } from "zod";

// ─── Patient ──────────────────────────────────────────────────────────────────
export const createPatientSchema = z.object({
  name:               z.string().min(1).max(200).trim(),
  empId:              z.string().min(1).max(50).trim(),
  company:            z.string().min(1).max(200).trim(),
  age:                z.number().int().min(1).max(120),
  gender:             z.enum(["Male", "Female", "Other"]),
  bloodGroup:         z.string().min(1).max(20).trim(),
  address:            z.string().max(300).trim().default(""),
  designation:        z.string().max(100).trim().default(""),
  identificationMark: z.string().max(200).trim().default(""),
});

// ─── Vitals — relaxed ranges for real-world values ────────────────────────────
const vitalsSchema = z.object({
  pulseRate:        z.number().min(0).max(300),
  bpSystolic:       z.number().min(0).max(300),
  bpDiastolic:      z.number().min(0).max(200),
  heightMetres:     z.number().min(0).max(3),
  weightKg:         z.number().min(0).max(500),
  chestInflationCm: z.number().min(0).max(100).optional().default(0),
  bmi:              z.number().min(0).max(200),    // 0 = not calculated yet
  temperatureF:     z.number().min(0).max(120),
  spo2Percent:      z.number().min(0).max(100),
});

// ─── Examination ──────────────────────────────────────────────────────────────
const examinationSchema = z.object({
  pallor:                  z.string().max(200).default("Not Observed"),
  lymphadenopathy:         z.string().max(200).default("No Any Lymphadenopathy"),
  respiratorySystem:       z.string().max(300).default("Air Entry Equal On Both Sides, No Added Sounds"),
  heart:                   z.string().max(200).default("S1,S2 Normal, No Murmur"),
  abdomen:                 z.string().max(200).default("Soft Nontender"),
  cns:                     z.string().max(200).default("No Abnormality Detected"),
  physicalHandicapped:     z.string().max(100).default("No"),
  eye: z.object({
    distantVisionRight: z.string().max(20).default("6/6"),
    distantVisionLeft:  z.string().max(20).default("6/6"),
    nightBlindness:     z.string().max(100).default("No Any Complaint"),
    colourVision:       z.string().max(50).default("Normal"),
  }).default({}),
  hearingAbility:          z.string().max(100).default("Present"),
  communicableDisease:     z.enum(["Yes", "No"]).default("No"),
  communicableDiseaseDesc: z.string().max(500).default(""),
  covid19Symptoms:         z.enum(["Yes", "No"]).default("No"),
  remarks:                 z.string().max(500).default("Nil"),
});

// ─── Doctor ───────────────────────────────────────────────────────────────────
const doctorSchema = z.object({
  name:               z.string().min(1).max(100).trim(),
  qualification:      z.string().max(50).trim().default("M.B.B.S."),
  registrationNumber: z.string().min(1).max(100).trim(),
});

// ─── Create Report — sNo is generated by backend, not required in request ─────
export const createReportSchema = z.object({
  patientId:   z.string().min(1),
  date:        z.string().regex(/^\d{2}\.\d{2}\.\d{4}$/, "Date must be DD.MM.YYYY"),
  vitals:      vitalsSchema,
  examination: examinationSchema,
  doctor:      doctorSchema,
  status:      z.enum(["draft", "submitted", "certified"]).default("submitted"),
});

export const updateReportSchema = createReportSchema.partial().extend({
  status: z.enum(["draft", "submitted", "certified"]).optional(),
});

export const reportQuerySchema = z.object({
  page:      z.string().optional().transform(v => parseInt(v ?? "1", 10)),
  limit:     z.string().optional().transform(v => Math.min(parseInt(v ?? "20", 10), 100)),
  status:    z.enum(["draft", "submitted", "certified", "all"]).optional().default("all"),
  patientId: z.string().optional(),
});

export type CreateReportInput = z.infer<typeof createReportSchema>;
export type UpdateReportInput = z.infer<typeof updateReportSchema>;